codecov:
  max_report_age: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
