codecov:
  max_report_age: false
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

flag_management:
  default_rules:
    carryforward: false

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
